'use strict';
/**
 * Mini wiki — an example consumer of openvibe-publishing. It owns its own database (an
 * openvibe-sdk/db handle: PostgreSQL in production, PGlite here) and its own publication state
 * (wiki_pages); the packages only supply the mechanics.
 *
 *   node examples/two-products/wiki/app.js      # http://127.0.0.1:4801 with an in-memory PGlite
 *
 * The schema is migrations/0001_initial.sql: the product's own tables plus the stores' schema(prefix)
 * DDL, applied with db.migrate() exactly as a service does (the file is generated by ../migrations.js).
 *
 * Uses: revisions (wiki_page_*), citations (wiki_citations), seo gate + redirects + sitemap +
 * Atom/JSON feeds, authorship (AI pages start as drafts), index-hooks (Search index events + product
 * events into wiki_outbox, in the same transaction as the change), ssr.
 */
const http = require('http');
const path = require('path');
// The package's public entry points, exactly as a product would import them.
const { createRevisionStore } = require('openvibe-publishing/revisions');
const { createCitationStore } = require('openvibe-publishing/citations');
const seo = require('openvibe-publishing/seo');
const authorship = require('openvibe-publishing/authorship');
const hooks = require('openvibe-publishing/index-hooks');
const ssr = require('openvibe-publishing/ssr');
const { slugify } = require('openvibe-publishing/taxonomy');

const POLICY = { minWords: 30, requireSources: true, minSources: 1 };

/** db: an openvibe-sdk/db handle the product owns. */
async function createWiki({ db, origin = 'https://openvibe.wiki', now = () => Date.now() } = {}) {
    const { sql } = db;
    await db.migrate({ dir: path.join(__dirname, 'migrations'), log: { log() {} } });
    const revisions = createRevisionStore(db, { prefix: 'wiki_page', now });
    const citations = createCitationStore(db, { prefix: 'wiki', now, revisions });
    const redirects = seo.createRedirectStore(db, { prefix: 'wiki_page', now });
    const reviews = authorship.createReviewLog(db, { prefix: 'wiki_page', now });
    const sequencer = hooks.createIndexSequencer(db, { prefix: 'wiki', now });

    const pathOf = (slug) => `/p/${slug}`;
    const urlOf = (slug) => seo.canonicalUrl(origin, pathOf(slug));
    const getPage = (h, id) => h.maybe(sql`SELECT * FROM wiki_pages WHERE id = ${id}`);
    const bySlug = (slug) => db.maybe(sql`SELECT * FROM wiki_pages WHERE slug = ${slug}`);

    /** The gate decision from facts already read (no query of its own). */
    function decideWith(page, rev, cites, review) {
        const rec = rev.meta.authorship;
        return seo.evaluate({
            state: page.state, visibility: page.visibility, canonicalUrl: urlOf(page.slug),
            text: ssr.markdownToText(rev.content), citationCount: cites.length,
            ...(rec ? authorship.gateFacts(rec, review) : {}),
        }, { policy: POLICY, now: now() });
    }

    async function decide(h, page, rev) {
        return decideWith(page, rev, await citations.forRevision(h, page.id, rev.number), await reviews.latest(h, page.id, rev.number));
    }

    async function document(h, page, rev, decision) {
        return hooks.buildIndexDocument({
            owner: 'wiki', type: 'page', id: page.id, revision: 0, state: page.state, visibility: page.visibility,
            canonicalUrl: urlOf(page.slug), title: rev ? rev.fields.title : page.slug, summary: rev ? ssr.markdownToText(rev.content, 160) : null,
            body: rev ? ssr.markdownToText(rev.content) : '', decision, acl: { subjects: [page.owner] },
            authorship: rev && rev.meta.authorship, citations: rev ? await citations.forRevision(h, page.id, rev.number) : [],
            facets: { content_revision: rev ? rev.number : 0 },
            publishedAt: page.published_at, updatedAt: page.updated_at,
        });
    }

    /**
     * After any change: send Search the current document (or tombstone) when it differs from the
     * last one sent, and the product event when the publication state moved. The stamp and both
     * events go into the outbox inside the caller's transaction `t`.
     */
    async function sync(t, before, page, actor) {
        const rev = page.published_revision ? await revisions.get(t, page.id, page.published_revision) : null;
        const decision = rev ? await decide(t, page, rev) : null;
        const sentBefore = await sequencer.current(t, 'wiki', 'page', page.id);
        const doc = await sequencer.stamp(t, await document(t, page, rev, decision));
        const out = [];
        if (doc.revision !== sentBefore) out.push(hooks.indexEvent({ document: doc, now: now() }));
        const action = hooks.actionFor(before && { state: before.state, visibility: before.visibility, revision: before.published_revision },
            { state: page.state, visibility: page.visibility, revision: page.published_revision });
        if (action) out.push(hooks.publicationEvent({ product: 'wiki', type: 'page', action, id: page.id, revision: page.published_revision || 0, actor, document: doc, decision, now: now() }));
        if (out.length) await t.exec(sql`INSERT INTO wiki_outbox ${sql.insert(out.map((env) => ({ envelope: JSON.stringify(env) })))}`);
        return out;
    }

    const api = {
        db, revisions, citations, redirects, reviews, policy: POLICY,

        createPage({ title, body, author, sources = [], authorship: rec = authorship.record({ mode: 'human', authors: [author] }) }) {
            return db.tx(async (t) => {
                const id = `pg_${slugify(title)}`;
                await t.exec(sql`INSERT INTO wiki_pages (id, slug, owner, updated_at) VALUES (${id}, ${slugify(title)}, ${author}, ${now()})`);
                const { revision } = await revisions.create(t, { entityId: id, expectedRevision: 0, content: body, fields: { title }, meta: { authorship: rec }, author });
                await citations.attachMany(t, id, revision.number, sources);
                return { id, revision: revision.number, initial: authorship.initialState(rec) };
            });
        },

        /** Edit: new revision; `keepSources` carries earlier citations forward, `sources` adds new ones. */
        edit(id, { expectedRevision, body, title, author, sources = [], keepSources = [] }) {
            return db.tx(async (t) => {
                const head = await revisions.head(t, id);
                const { revision } = await revisions.create(t, {
                    entityId: id, expectedRevision, content: body, fields: { title: title || head.fields.title },
                    meta: { authorship: authorship.record({ mode: 'human', authors: [author] }) }, author,
                });
                if (keepSources.length) await citations.carryForward(t, { entityId: id, fromRevision: head.number, toRevision: revision.number, ids: keepSources });
                await citations.attachMany(t, id, revision.number, sources);
                return revision.number;
            });
        },

        revert(id, { toRevision, expectedRevision, author }) {
            return db.tx(async (t) => {
                const { revision } = await revisions.revert(t, { entityId: id, toRevision, expectedRevision, author });
                await citations.carryForward(t, { entityId: id, fromRevision: toRevision, toRevision: revision.number });
                return revision.number;
            });
        },

        publish(id, { revision, actor }) {
            return db.tx(async (t) => {
                const before = await getPage(t, id);
                const rev = await revisions.get(t, id, revision);
                const rec = rev.meta.authorship;
                const ok = authorship.canPublish(rec, await reviews.latest(t, id, revision));
                if (!ok.ok) throw Object.assign(new Error(`cannot publish: ${ok.reason}`), { status: 409, code: ok.reason });
                const page = await t.one(sql`UPDATE wiki_pages SET state = 'published', published_revision = ${revision}, published_at = COALESCE(published_at, ${now()}), updated_at = ${now()}
                    WHERE id = ${id} RETURNING *`);
                return sync(t, before, page, actor);
            });
        },

        setVisibility(id, visibility, { actor }) {
            return db.tx(async (t) => {
                const before = await getPage(t, id);
                const page = await t.one(sql`UPDATE wiki_pages SET visibility = ${visibility}, updated_at = ${now()} WHERE id = ${id} RETURNING *`);
                return sync(t, before, page, actor);
            });
        },

        rename(id, newTitle) {
            return db.tx(async (t) => {
                const before = await getPage(t, id);
                const slug = slugify(newTitle);
                await redirects.recordMove(t, id, pathOf(before.slug), pathOf(slug));
                const page = await t.one(sql`UPDATE wiki_pages SET slug = ${slug}, updated_at = ${now()} WHERE id = ${id} RETURNING *`);
                await sync(t, before, page, 'svc:wiki'); // the canonical URL changed: Search gets a new revision
                return slug;
            });
        },

        remove(id, { actor }) {
            return db.tx(async (t) => {
                const before = await getPage(t, id);
                const page = await t.one(sql`UPDATE wiki_pages SET state = 'deleted', updated_at = ${now()} WHERE id = ${id} RETURNING *`);
                return sync(t, before, page, actor);
            });
        },

        async outbox() { return (await db.many(sql`SELECT envelope FROM wiki_outbox ORDER BY id`)).map((r) => r.envelope); },

        /** Every published page with its live revision and gate decision: four queries however many pages (no N+1). */
        async published() {
            const pages = await db.many(sql`SELECT * FROM wiki_pages WHERE state = 'published' ORDER BY published_at DESC, id LIMIT 1000`);
            const refs = pages.map((p) => ({ entityId: p.id, revision: p.published_revision }));
            const [revs, cites, checks] = await Promise.all([revisions.getMany(refs), citations.forRevisions(refs), reviews.latestMany(refs)]);
            return pages.map((page, i) => ({ page, rev: revs[i], decision: decideWith(page, revs[i], cites[i], checks[i]) }));
        },

        async sitemapXml() {
            return seo.sitemap((await api.published()).map(({ page, rev, decision }) => ({ loc: urlOf(page.slug), lastmod: rev.createdAt, decision }))).files[0];
        },

        async feedItems() {
            return (await api.published()).map(({ page, rev, decision }) => ({
                id: `tag:openvibe.wiki,2026:page/${page.id}`, url: urlOf(page.slug), title: rev.fields.title,
                summary: ssr.markdownToText(rev.content, 200), contentHtml: ssr.renderMarkdown(rev.content, { rel: 'noopener' }),
                published: page.published_at, updated: rev.createdAt, decision,
            }));
        },

        async atom() {
            // Atom needs a feed-level <updated>: the last real change to any page (never "now").
            const last = await db.value(sql`SELECT max(updated_at) AS t FROM wiki_pages`);
            return seo.atomFeed({ title: 'Mini wiki: recent pages', link: origin + '/', feedUrl: `${origin}/feed.atom`, updated: last }, await api.feedItems());
        },
        async jsonFeedDoc() { return seo.jsonFeed({ title: 'Mini wiki: recent pages', link: origin + '/', feedUrl: `${origin}/feed.json` }, await api.feedItems()); },

        async renderPage(page) {
            const rev = await revisions.get(page.id, page.published_revision);
            const decision = await decide(db, page, rev);
            const cites = await citations.forRevision(page.id, rev.number);
            const disclosure = authorship.disclosure(rev.meta.authorship, await reviews.latest(page.id, rev.number));
            const crumbs = [{ name: 'Wiki', url: `${origin}/` }, { name: rev.fields.title, url: urlOf(page.slug) }];
            const head = seo.metaTags({ title: rev.fields.title, description: ssr.markdownToText(rev.content, 160), decision, type: 'article',
                jsonLd: [seo.structuredData.article({ headline: rev.fields.title, url: urlOf(page.slug), dateModified: rev.createdAt,
                    datePublished: page.published_at ? new Date(page.published_at).toISOString() : null, citations: cites }), seo.structuredData.breadcrumbs(crumbs)].filter(Boolean) });
            return String(ssr.html`<!doctype html><html lang="en"><head><meta charset="utf-8">${ssr.raw(head)}</head><body>
${ssr.raw(ssr.breadcrumbsHtml(crumbs))}
<article><h1>${rev.fields.title}</h1>${disclosure ? ssr.html`<p class="disclosure">${disclosure.long}</p>` : ''}
${ssr.raw(ssr.renderMarkdown(rev.content, { rel: 'noopener' }))}
<p>Revision ${rev.number}, ${ssr.raw(ssr.timeTag(rev.createdAt))} · <a href="${pathOf(page.slug)}/history">history</a></p>
<section><h2>Sources</h2><ol>${cites.map((c) => ssr.html`<li>${c.url ? ssr.html`<a href="${c.url}" rel="noopener">${c.title || c.url}</a>` : c.sourceItemId}${c.retrievedAt ? ssr.html`, retrieved ${ssr.raw(ssr.timeTag(c.retrievedAt))}` : ''}${c.licenseNote ? ` (${c.licenseNote})` : ''}</li>`)}</ol></section>
</article></body></html>`);
        },

        /** Node http handler: pages, 301/410 history, sitemap, feeds. No JavaScript anywhere. */
        handler(req, res) {
            const send = (status, type, body, headers = {}) => { res.writeHead(status, { 'Content-Type': type, ...headers }); res.end(body); };
            api.route(req, send).catch((err) => { if (!res.headersSent) send(500, 'text/plain', 'Server error'); console.error(err); });
        },

        async route(req, send) {
            const url = new URL(req.url, origin);
            if (url.pathname === '/sitemap.xml') return send(200, 'application/xml', await api.sitemapXml());
            if (url.pathname === '/feed.atom') return send(200, 'application/atom+xml', await api.atom());
            if (url.pathname === '/feed.json') return send(200, 'application/feed+json', JSON.stringify(await api.jsonFeedDoc()));
            if (url.pathname === '/robots.txt') return send(200, 'text/plain', seo.robotsTxt({ sitemaps: [`${origin}/sitemap.xml`] }));
            const m = url.pathname.match(/^\/p\/([^/]+)(\/history)?$/);
            if (!m) return send(404, 'text/plain', 'Not found');
            const page = await bySlug(decodeURIComponent(m[1]));
            if (!page) {
                const r = await redirects.resolve(url.pathname.replace(/\/history$/, ''), { currentPath: async (id) => { const p = await getPage(db, id); return p && p.state !== 'deleted' ? pathOf(p.slug) : null; } });
                if (r && r.status === 301) return send(301, 'text/plain', 'Moved', { Location: r.location + (m[2] || '') });
                if (r && r.status === 410) return send(410, 'text/plain', 'Gone');
                return send(404, 'text/plain', 'Not found');
            }
            if (page.state === 'deleted') return send(410, 'text/plain', 'Gone');
            if (page.state !== 'published' || page.visibility === 'private' || page.visibility === 'gated') return send(404, 'text/plain', 'Not found');
            if (m[2]) {
                const list = (await revisions.list(page.id)).map((r) => ssr.html`<li>r${r.number} ${r.kind} ${ssr.raw(ssr.timeTag(r.createdAt))}</li>`);
                return send(200, 'text/html; charset=utf-8', String(ssr.html`<!doctype html><title>History</title><meta name="robots" content="noindex"><ol>${list}</ol>`));
            }
            return send(200, 'text/html; charset=utf-8', await api.renderPage(page));
        },

        /** The database belongs to whoever opened it; the app holds nothing else. */
        close() {},
    };
    return api;
}

module.exports = { createWiki };

if (require.main === module) {
    (async () => {
        const { createDb } = require('openvibe-sdk/db');
        const db = createDb({ pglite: true, service: 'mini-wiki' });
        const wiki = await createWiki({ db, origin: 'http://127.0.0.1:4801' });
        const { id } = await wiki.createPage({
            title: 'Rye', author: 'usr_01J8Z6Q3KX0000000000000000',
            body: 'Rye is a grass grown extensively as a grain, a cover crop and a forage crop. It is closely related to wheat and barley, and its grain is used for flour, bread, beer, whiskey and animal fodder.',
            sources: [{ url: 'https://en.wikipedia.org/wiki/Rye', title: 'Rye — Wikipedia', licenseNote: 'CC BY-SA 4.0' }],
        });
        await wiki.publish(id, { revision: 1, actor: 'usr_01J8Z6Q3KX0000000000000000' });
        http.createServer(wiki.handler).listen(4801, '127.0.0.1', () => console.log('mini wiki on http://127.0.0.1:4801/p/rye (in-memory PGlite)'));
    })().catch((err) => { console.error(err); process.exit(1); });
}
