'use strict';
/**
 * Mini blog — the second example consumer of openvibe-publishing, with its own database and its
 * own publication state (blog_posts). Different editorial rules from the wiki (sources optional,
 * shorter minimum), same shared mechanics.
 *
 *   node examples/two-products/blog/app.js      # http://127.0.0.1:4811 with an in-memory PGlite
 *
 * The schema is migrations/0001_initial.sql (generated by ../migrations.js), applied with db.migrate().
 *
 * Uses: revisions (blog_post_*), citations (blog_post_citations), taxonomy (blog_terms), schedule
 * (blog_schedule_jobs), media attachments (blog_post_attachments), seo gate + sitemap + RSS/JSON
 * Feed, ssr.
 */
const http = require('http');
const path = require('path');
const { createRevisionStore } = require('openvibe-publishing/revisions');
const { createCitationStore } = require('openvibe-publishing/citations');
const { createTaxonomy, slugify } = require('openvibe-publishing/taxonomy');
const { createScheduler } = require('openvibe-publishing/schedule');
const { createAttachmentStore, figureHtml } = require('openvibe-publishing/media');
const seo = require('openvibe-publishing/seo');
const ssr = require('openvibe-publishing/ssr');

const POLICY = { minWords: 20, requireSources: false };

/** db: an openvibe-sdk/db handle the product owns. */
async function createBlog({ db, origin = 'https://openvibe.blog', mediaOrigin = 'https://openvibe.media', now = () => Date.now() } = {}) {
    const { sql } = db;
    await db.migrate({ dir: path.join(__dirname, 'migrations'), log: { log() {} } });
    const revisions = createRevisionStore(db, { prefix: 'blog_post', now });
    const citations = createCitationStore(db, { prefix: 'blog_post', now, revisions });
    const taxonomy = createTaxonomy(db, { prefix: 'blog', now });
    const scheduler = createScheduler(db, { prefix: 'blog', now, leaseMs: 60000 });
    const media = createAttachmentStore(db, { prefix: 'blog_post', now });

    const urlOf = (slug) => seo.canonicalUrl(origin, ['posts', slug]);

    function decideWith(post, rev, cites) {
        return seo.evaluate({
            state: post.state, visibility: post.visibility, canonicalUrl: urlOf(post.slug),
            text: ssr.markdownToText(rev.content), citationCount: cites.length,
        }, { policy: POLICY, now: now() });
    }

    /** The idempotent effect a scheduled job applies: "revision N is the published one". */
    async function applyPublish(id, revision) {
        const changed = await db.exec(sql`UPDATE blog_posts SET state = 'published', published_revision = ${revision}, published_at = COALESCE(published_at, ${now()}), updated_at = ${now()}
            WHERE id = ${id} AND (state IS DISTINCT FROM 'published' OR published_revision IS DISTINCT FROM ${revision}::integer)`);
        return { changed };
    }

    const api = {
        db, revisions, citations, taxonomy, scheduler, media, policy: POLICY,

        draft({ title, body, authorName = null, tags = [], sources = [] }) {
            return db.tx(async (t) => {
                const slug = slugify(title);
                const id = `post_${slug}`;
                await t.exec(sql`INSERT INTO blog_posts (id, slug, author_name, updated_at) VALUES (${id}, ${slug}, ${authorName}, ${now()})`);
                const { revision } = await revisions.create(t, { entityId: id, expectedRevision: 0, content: body, fields: { title } });
                await citations.attachMany(t, id, revision.number, sources);
                await taxonomy.setTerms(t, id, 'tag', tags);
                return { id, revision: revision.number };
            });
        },

        async edit(id, { expectedRevision, body, title }) {
            const head = await revisions.head(id);
            return (await revisions.create({ entityId: id, expectedRevision, content: body, fields: { title: title || head.fields.title } })).revision.number;
        },

        publishNow(id, revision) { return applyPublish(id, revision); },
        schedulePublish(id, { revision, at }) { return scheduler.schedule({ entityId: id, action: 'publish', runAt: at, revision }); },
        runScheduled(worker) {
            return scheduler.runDue({ worker, handler: (job) => (job.action === 'publish' ? applyPublish(job.entityId, job.revision) : null) });
        },
        async setVisibility(id, visibility) { await db.exec(sql`UPDATE blog_posts SET visibility = ${visibility}, updated_at = ${now()} WHERE id = ${id}`); },

        /** Published posts with their live revision, citations and gate decision: three queries however many posts. */
        async published() {
            const posts = await db.many(sql`SELECT * FROM blog_posts WHERE state = 'published' ORDER BY published_at DESC, id LIMIT 1000`);
            const refs = posts.map((p) => ({ entityId: p.id, revision: p.published_revision }));
            const [revs, cites] = await Promise.all([revisions.getMany(refs), citations.forRevisions(refs)]);
            return posts.map((post, i) => ({ post, rev: revs[i], decision: decideWith(post, revs[i], cites[i]) }));
        },

        async feedItems() {
            const list = await api.published();
            const tags = await taxonomy.termsForMany(list.map(({ post }) => post.id), 'tag');
            return list.map(({ post, rev, decision }, i) => ({
                id: `tag:openvibe.blog,2026:post/${post.id}`, url: urlOf(post.slug), title: rev.fields.title,
                summary: ssr.markdownToText(rev.content, 200), contentHtml: ssr.renderMarkdown(rev.content),
                published: post.published_at, updated: rev.createdAt, decision,
                authors: post.author_name ? [{ name: post.author_name }] : [],
                tags: tags[i].map((t) => t.name),
            }));
        },
        async rss() { return seo.rssFeed({ title: 'Mini blog', link: `${origin}/`, description: 'Posts from the mini blog example', feedUrl: `${origin}/feed.xml` }, await api.feedItems()); },
        async jsonFeedDoc() { return seo.jsonFeed({ title: 'Mini blog', link: `${origin}/`, feedUrl: `${origin}/feed.json` }, await api.feedItems()); },
        async sitemapXml() { return seo.sitemap((await api.published()).map(({ post, rev, decision }) => ({ loc: urlOf(post.slug), lastmod: rev.createdAt, decision }))).files[0]; },

        async renderPost(post) {
            const rev = await revisions.get(post.id, post.published_revision);
            const decision = decideWith(post, rev, await citations.forRevision(post.id, rev.number));
            const figures = (await media.list(post.id)).map((a) => ssr.raw(figureHtml(a, { urlFor: (id) => `${mediaOrigin}/o/${id}` })));
            const tags = await taxonomy.termsFor(post.id, 'tag');
            const head = seo.metaTags({ title: rev.fields.title, description: ssr.markdownToText(rev.content, 160), decision, type: 'article',
                jsonLd: seo.structuredData.article({ type: 'BlogPosting', headline: rev.fields.title, url: urlOf(post.slug),
                    datePublished: post.published_at ? new Date(post.published_at).toISOString() : null, dateModified: rev.createdAt,
                    authors: post.author_name ? [{ name: post.author_name }] : [], keywords: tags.map((t) => t.name) }) });
            return String(ssr.html`<!doctype html><html lang="en"><head><meta charset="utf-8">${ssr.raw(head)}${ssr.raw(seo.feedLinks([{ type: 'rss', href: '/feed.xml', title: 'RSS' }]))}</head><body>
<article><h1>${rev.fields.title}</h1><p>${post.author_name ? ssr.html`By ${post.author_name} · ` : ''}${ssr.raw(ssr.timeTag(post.published_at))}</p>
${figures}
${ssr.raw(ssr.renderMarkdown(rev.content))}
<p>${tags.map((t) => ssr.html`<a href="/tags/${t.slug}">#${t.name}</a> `)}</p></article></body></html>`);
        },

        handler(req, res) {
            const send = (status, type, body) => { res.writeHead(status, { 'Content-Type': type }); res.end(body); };
            api.route(req, send).catch((err) => { if (!res.headersSent) send(500, 'text/plain', 'Server error'); console.error(err); });
        },

        async route(req, send) {
            const url = new URL(req.url, origin);
            if (url.pathname === '/feed.xml') return send(200, 'application/rss+xml', await api.rss());
            if (url.pathname === '/feed.json') return send(200, 'application/feed+json', JSON.stringify(await api.jsonFeedDoc()));
            if (url.pathname === '/sitemap.xml') return send(200, 'application/xml', await api.sitemapXml());
            const m = url.pathname.match(/^\/posts\/([^/]+)$/);
            const post = m && await db.maybe(sql`SELECT * FROM blog_posts WHERE slug = ${decodeURIComponent(m[1])}`);
            if (!post || post.state !== 'published' || post.visibility === 'private' || post.visibility === 'gated') return send(404, 'text/plain', 'Not found');
            return send(200, 'text/html; charset=utf-8', await api.renderPost(post));
        },

        /** The database belongs to whoever opened it; the app holds nothing else. */
        close() {},
    };
    return api;
}

module.exports = { createBlog };

if (require.main === module) {
    (async () => {
        const { createDb } = require('openvibe-sdk/db');
        const db = createDb({ pglite: true, service: 'mini-blog' });
        const blog = await createBlog({ db, origin: 'http://127.0.0.1:4811' });
        const { id, revision } = await blog.draft({ title: 'First loaf', authorName: 'Alex', tags: ['bread', 'rye'],
            body: 'My first rye loaf came out dense but tasty. Next time I will give the starter a longer rise and bake it a little hotter.' });
        await blog.publishNow(id, revision);
        http.createServer(blog.handler).listen(4811, '127.0.0.1', () => console.log('mini blog on http://127.0.0.1:4811/posts/first-loaf (in-memory PGlite)'));
    })().catch((err) => { console.error(err); process.exit(1); });
}
